# DO NOT EDIT THIS FILE!
#
# Python module TestModule generated by omniidl

import omniORB
omniORB.updateModule("TestModule")

# ** 1. Stub files contributing to this module
import testService_idl

# ** 2. Sub-modules

# ** 3. End
